CREATE TABLE IF NOT EXISTS USERS
(USER_ID INTEGER NOT NULL AUTO_INCREMENT,
 DISPLAYNAME VARCHAR(255),
 USERNAME VARCHAR(255) NOT NULL UNIQUE,  
 PASSWORD VARCHAR(255) NOT NULL, 
 EMAIL VARCHAR(255), 
 MOBILENUMBER VARCHAR(255),
 PRIMARY KEY (USER_ID));
 
 CREATE TABLE IF NOT EXISTS ROLES
(ROLE_ID INTEGER NOT NULL AUTO_INCREMENT,
 ROLENAME VARCHAR(255) NOT NULL UNIQUE,
 PRIMARY KEY (ROLE_ID));
 
 CREATE TABLE IF NOT EXISTS ACCESSMAPPING
(ACCESSMAPPING_ID INTEGER NOT NULL AUTO_INCREMENT,
USER_ID INTEGER NOT NULL,
 ROLE_ID INTEGER NOT NULL,
 PRIMARY KEY (ACCESSMAPPING_ID),
 FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
 );