CREATE TABLE IF NOT EXISTS USER_DETAILS 
(ID INTEGER NOT NULL AUTO_INCREMENT,
 EMAIL VARCHAR(255), 
 FIRST_NAME VARCHAR(255), 
 LAST_NAME VARCHAR(255), 
 PASSWORD VARCHAR(255), 
 PRIMARY KEY (ID));